name = "SimplePipelines"
uuid = "01cec563-5001-4a35-82a7-0a4ff79c2cf4"
version = "0.1.0"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com>"]

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[compat]
Documenter = "1.16.1"
julia = "1.9"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["Documenter"]
test = ["Test"]
