name = "SimplePipelines"
uuid = "01cec563-5001-4a35-82a7-0a4ff79c2cf4"
version = "0.1.0"
authors = ["Mateusz Kaduk <mateusz.kaduk@gmail.com>"]

[deps]
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
julia = "1.9"
Serialization = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
